import io

path = "migrations/versions/0f26a7a8c59e_add_is_downloaded_to_orders.py"
with io.open(path, "r", encoding="utf-8") as f:
    content = f.read()

old = """def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_downloaded', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###"""

new = """def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_downloaded', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('orders', 'is_downloaded', server_default=None)
    # ### end Alembic commands ###"""

c = content.count(old)
print(f"Anchor found {c} time(s)")
if c == 1:
    content = content.replace(old, new)
    print("Migration fixed with server_default")
else:
    print("WARNING: anchor not found")

with io.open(path, "w", encoding="utf-8") as f:
    f.write(content)
