"""add is_downloaded to orders

Revision ID: 0f26a7a8c59e
Revises: 
Create Date: 2026-08-03 10:34:33.744020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f26a7a8c59e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_downloaded', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('orders', 'is_downloaded', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_downloaded')
    # ### end Alembic commands ###
